name: build
on:
    push:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@main
            with:
                submodules: true
          - run: make
          - run: make build-deb
          - run: mv smolbox smolbox-glibc-x86_64
          - uses: actions/upload-artifact@v7
            with:
                name: smolbox-x86_64
                path: smolbox-x86_64
                if-no-files-found: error
                archive: false
          - uses: actions/upload-artifact@v7
            with:
                name: smolbox-x86_64.deb
                path: smolbox-x86_64.deb
                if-no-files-found: error
                archive: false
